# Generated by Django 2.2.7 on 2020-01-21 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=200)),
                ('course_fees', models.IntegerField()),
                ('course_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dp', models.ImageField(upload_to='student/')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('status', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('studentCourse_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_month', models.CharField(max_length=200)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('payment_doc', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.Student')),
            ],
        ),
    ]
