# Generated by Django 2.2.7 on 2020-01-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
